# Cargo.toml (workspace root)
[workspace]
resolver = "3"
members = [
    "crates/cli",
    "crates/core",
    "crates/web",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Klaus Bertram"]
repository = "https://github.com/spectra-data/tecton"
rust-version = "1.98.1"

[workspace.dependencies]
# Internal crates
#tecton-core = { path = "crates/core" }
#tecton-web = { path = "crates/web" }
#tecton-cli = { path = "crates/cli" }


# Core
tantivy = { version = "0.26", features = [ "default" ,"stemmer", "zstd-compression","columnar-zstd-compression"] }
ulid = "3.0"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["default","env-filter", "fmt", "json"] }

metrics = "0.24"
metrics-exporter-prometheus = "0.18"
opentelemetry = { version = "0.32", features = ["trace"] }
opentelemetry-otlp = { version = "0.32", features = ["metrics","grpc-tonic"] }
opentelemetry_sdk = { version = "0.32", features = ["trace"] }
tracing-opentelemetry= { version="0.33"}
anyhow = "1.0"
tokio = { version = "1.53", features = ["full","macros","rt"] }
parking_lot = "0.12"
dashmap = "6.2"
num_cpus = "1.17"
whichlang ="0.1"
const_format = "0.2"

fast-hnsw = { version = "1"} #, features = ["serde", "rayon"] } # rayon for parallel build
tokenizers = "0.23"
hf-hub = { version = "1", features = ["socks","blocking"] }
ahash = "0.8"

once_cell = "1.21"   # Global model initialization
rayon = "1.12"

# CLI
clap = { version = "4.6", features = ["derive", "env", "string"] }
clap_complete = "4.6"
indicatif = "0.16"
console = "0.16"
comfy-table = "7.2"
csv = "1.4"
toml="1.1"

# Web
axum = { version = "0.8", features = ["ws","http2"] }
tower = { version = "0.5", features = ["util", "timeout", "limit"] }
tower-http = { version = "0.7", features = ["full"] }
hyper = { version = "1.11", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
uuid = { version = "1.0", features = ["serde", "v4"] }

utoipa = { version = "5.5", features = ["axum_extras","chrono"] }
utoipa-axum = { version = "0.2" }
utoipa-swagger-ui = { version = "9.0", features = ["axum"] }
utoipa-redoc = { version = "6.0", features = ["axum"] }
utoipa-rapidoc = { version = "6.0", features = ["axum"] }
utoipa-scalar = { version = "0.3", features = ["axum"] }
axum-extra = { version = "0.12", features = ["typed-header"] }
axum-server= { version="0.8" , features = ["tls-rustls"]}
walkdir = "2.5"


# Config
figment = { version = "0.10", features = ["toml", "yaml", "env"] }
# Test dependencies
